hash-format = "sha256"

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "da42d2a6e6e3f7bd10df625ab23d6ba8a50ecb3545c1c3c6bda4f826caa5d51b"
metafile = true

[[files]]
file = "mods/alexs-caves.pw.toml"
hash = "6f864eef65f9a38f57eb0cc6fc71469b36ea70444a10c3e27502d617c5eaf917"
metafile = true

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "40bab1828ae2b4d755db64f1c887a2fe06171fad6ab54d4a1863ca5c30ff9b55"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "a966c425617e0583ccadc2fe7f521a53833c93f4aacd9c89c24ad7cc76eca97a"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
hash = "0f4c2198603cd84a14dc6741729d0b0dcf509574776e620c36c3e7180082db32"
metafile = true

[[files]]
file = "mods/aquaculture.pw.toml"
hash = "c4ba20c9dc88687865d5c9dd2b6e0043a69055c46b8fd935dd74c43ee56b5428"
metafile = true

[[files]]
file = "mods/architects-palette.pw.toml"
hash = "ea0e1047f953916c926acb92182c550ddfb93d1ac67b490a0d6b3f4627ba80aa"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5e9edd1fd2395f14a0c8a4acbdbdd61e1047be1f0033deb3140d2ce0d093e9d8"
metafile = true

[[files]]
file = "mods/athena.pw.toml"
hash = "9638d8a308563842fd989970919a51f37ed1bcc82372bff47fc5a5c2e6de738e"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "585a3071c68587c3c041832210a58e74e7701162dbc360d47956655ca1a6438e"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "83ba38ab1e5b583227e9d37b8fea91ac1fcb4e2f67ba86800c5d7aa4024d2993"
metafile = true

[[files]]
file = "mods/blockui.pw.toml"
hash = "a8f0762eb0b57696a445cc9f9b8968de9492de538595e27d756bd7fe39ca1a9f"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "008c942efc2e2ec221dd1a760b4a50e2f24ede37747731ba794f5e845554adcb"
metafile = true

[[files]]
file = "mods/build-guide.pw.toml"
hash = "c3f4c6c614afc0718e2df0f29eb80df691eabd7fe470bae675bf97ac6e605109"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
hash = "e5df83a3dd1686106741d1d61da5869aed0537c2931a40234e1b3bd2d09e1971"
metafile = true

[[files]]
file = "mods/chalk.pw.toml"
hash = "2fd7cb889d3b994a174a16befb63b9e8b2fee350ae1a338cd7651cb8e171089e"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "71a33fe41bead909b3e95643351ef8015def70d3cb083916469f492f66434b45"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "0e17f9758f6f67ef87aa6f8d5afc47901521a05904cd8470ef65063b48e69d73"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "0c8838dba7d2090968ca9ec633260d42ca16f1df186a780bd5965994541d9f74"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "96204145e12506e0625d8b9bfa05aad54e9a62fd511bae39f0d57fcb5e39f4cc"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "e3173aaa4e9078ad7ace2b9ef43ce15ce9919c0b566d8830cea87264f92b3a6a"
metafile = true

[[files]]
file = "mods/coastal-waves.pw.toml"
hash = "e0a828d55d47da6c837299523af369845eb2a277bdbaf71197f638864dfb4387"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "58bf97ca61f74ea9a540f6e6090aef631155748c49b83a7a338b34d8dece9109"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "c4624bc1de86bbe9739fc2e9d4a580dd52c1b7e1ac23dee8c01344307cc2cb57"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
hash = "d62480bc696affd0a714d4cd74b5dc64a072b9d67d505b52df87ebcdf9650a79"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
hash = "a92288574aeb3b2387d8c423b980321efa0f486074d6167aa30195a09d930369"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "fee58a333eaf51d4862fee34fe8ba7cb70140500023e06aca3c9fcf0e0f34719"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "c2ee46d175b9a6ab59dcbf24567fcb68253d6b039dbb2ce3dac0c1332aac8fa9"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "0971029a9e6cbc93c8fd694f97942c566979973f3d98023b730b1d436f617220"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "9d7971a7af2ff4a96a0e5aede76f9cf8dc978da601e2754f79d6ec8631125bb9"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "8a5f33277995fccd2be6793c4fba1b5d657983be32f0b47e4afab4eac70b8ab8"
metafile = true

[[files]]
file = "mods/croptopia.pw.toml"
hash = "d8fde87d322c7d8e841658090d41c33120c72b4e6724af94a9fd3cc41603234c"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "2eb26b157c4159bfeff6a00147afa35284397d558f84b55367d1a41064d7456a"
metafile = true

[[files]]
file = "mods/decorative-blocks.pw.toml"
hash = "02e3f47ff5a2fa074996387e14c81718e5c4df16dbe75ba1e1021157352f7815"
metafile = true

[[files]]
file = "mods/domum-ornamentum.pw.toml"
hash = "633b13c5912472982f53776c205117edbbf4b13b4de1975c37c42b6cf79624cf"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "a1575677daaaf6ea6dac12e5a10073e34025e5ca2c35b6d36ad4a5a0edbc0e82"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d48a1ea93de8cd5febb95ba52989d8d9ab4e998cfbdf9c1076a9f2e571d2fcbe"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6843022335e0f27b000ff90bf6641c5299594f5ca06331abf298b5122c6b9bcc"
metafile = true

[[files]]
file = "mods/epherolib.pw.toml"
hash = "fadaae47087ff0af2442bed6c9978eaa14f2926990738d81b5ce382d4c4a86fa"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "adcd67c419f4c88858298958287b1658e9a81b7d50c6794769ca01c8b856d3a6"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "067fc433511066d18b1795b86c9856246a8da7f9a4316afd6b25e5eee181f660"
metafile = true

[[files]]
file = "mods/farmers-respite.pw.toml"
hash = "49431cb48a66b264c2cb7702c7bb80155d1a59a42d384348e30700ce0ebc1e4c"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "5bd0506bc0be25116b234f2b5af9447f60d82ae1cb6c5be4e12d8841f6c2501c"
metafile = true

[[files]]
file = "mods/fix-gpu-memory-leak.pw.toml"
hash = "c4032dc8c4f85576b7d89f719aa56241fbcdede45d3fc8bad43c86e499d01a67"
metafile = true

[[files]]
file = "mods/ftb-chunks-forge.pw.toml"
hash = "0e753f0aea9277eba730d4a55929f244f9d7c9d15cc5e9bd96b4669e531f6de2"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "691798dd9acfd386bc9332249cd4c1291c646af4d97999090ec0528d9bb35c88"
metafile = true

[[files]]
file = "mods/ftb-teams-forge.pw.toml"
hash = "450e23b3e692360eee6fd55fc640b391eff8f4e5714ccc69bafb837685ae8e96"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "e17f96677912ca1e42ab05ba1e959226c7b5244f6a24eb573ace63f57e6c222f"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "c46659c3e873e0ca121f5215991ae8bc989132a3fea0c2da9eed0f22a947b2b9"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "5cc92eb0e58c2afbfd625d727d80da1d1c84500ec962bb22f5be28b864f18551"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "b9a7e71472f5f88229bf2f9e214b223b3900052bdc56075906d7a22acf74568c"
metafile = true

[[files]]
file = "mods/hypertubes.pw.toml"
hash = "7c62eec6689e4b771b835e8fe732dd924ff1a560818bf35e11f6d13b4b479878"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c949e6e0d6a70b8693ef48f8f205cb4fb967cc7c2ecbe029ffe7809e36ad5138"
metafile = true

[[files]]
file = "mods/interiors.pw.toml"
hash = "588e222f5cf824fb8317bd3800752c8a4a86f3c707f70b35420f8c9a9599fe43"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "fb8b143630e9d758531fa727594c76b8735f1c7a8ecc4911307c8e71e99b70a1"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "8f359d190506a6f824763b8e7c390d9e22204ef11e3ffa5ef980000d17e2c2b6"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "94a0ed0630ad6e53af1e317e86a195672f4627552fde677396ac94eefce6ffc6"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "40026875ee9b7d25a4ece48faa2b70a338100e87a689d5a8d4ba1ee608b878f6"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "873d23ad2ce05e3e92a05e011f3f9a375a745a4ca6ed4c9fffb0518fc8255bf7"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "ee79f551b7aede4b923fc6df137c4ebbb1dd21eb80a3aaba6da8be93ac5010e7"
metafile = true

[[files]]
file = "mods/light-overlay.pw.toml"
hash = "ec1dbea2c473bfd08357e3a31745ba28046debee77242e9c401169ddbc88bcd3"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "3706f6817a641198fc325d578d189d502af7c3444148a72e4dc23f214c3611a1"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "7c411a566d022680769ddb8323984fff292ddeb35e7d8fcfe2cc41b9885d9557"
metafile = true

[[files]]
file = "mods/minecolonies.pw.toml"
hash = "2d9cb51b1fe897e0bb6f5c3a4edfc7ba00dead8863eea82f8ed0df662edf707c"
metafile = true

[[files]]
file = "mods/minecraft-transit-railway.pw.toml"
hash = "132d168b3cfe4f52314da48c734d69a1dca3095b3d5a9214f7d793de4e0d2e52"
metafile = true

[[files]]
file = "mods/miners-delight-plus.pw.toml"
hash = "8a459a2534f09d18581fa154a84f428b1eaf1721fc8493ebe1e80df490e7502c"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "373b18020e519fa602dc3e5ecc7d9d1523a353ddec85b20fe8dbbad23d4e7db2"
metafile = true

[[files]]
file = "mods/multi-piston.pw.toml"
hash = "9895bf13e14fbb0b5284f7ad800b1fb3c7d4c373306231d5c6f95a282079fcbe"
metafile = true

[[files]]
file = "mods/nethers-delight.pw.toml"
hash = "43ff48404322ec170ef9a931bc2f95cc9b488e2834934e2af6c5e0ebebc5fb9c"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "5ef885f9912ff6aa73db254b63a3cd22520f06261bc3c38e7c92f449806a9044"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8c65958007f81cdf1a57dac999ec7ffdde17cce6154c9a2f75bbb389fd11efbf"
metafile = true

[[files]]
file = "mods/rechiseled-chipped.pw.toml"
hash = "6404fb65e80b83afe92bad0d4562253d2b7f821114e5574fcf7eb58e08b6da66"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
hash = "3e8c59c1817babb68d49af1bd816d6d00ffbaa8343968ad324996a0d5deb9c69"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "e242387207a2538b5ccb55697174c65e549e1eb2fef9da37e1ad3734e0372b65"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "ef0264b7d819848f72ab2f34643306187e712965a8246e1f733e1bd39d8fd681"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "ca4411ac6d8a9a892948bb63cd0ba52ae5523ca5e257632d6ae8c933b660c5ee"
metafile = true

[[files]]
file = "mods/ritchies-projectile-library.pw.toml"
hash = "8206df6c97f3b0696ca143240084eea614dc1f404ab917dde9c5f156cebafa02"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
hash = "b8c2ba91c889b159d1b85c11293927958401b4df1898dced176bb70984a22259"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "086ae6b5cfa8a07be194343117c92c8139275a8dac28d4c3476081a0eb1d3386"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "4337bb9f8d504a42da9ca4d56041e1353aa2f84e5470308e3806ce5650691044"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "e4b99d45d1cfb55b0ecd2aa78c56958b57460e63b637448017df60b2412e77d9"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "d0e1a79dbcda8499e0f12f4adaa5503f9bbc84a6274ce07b3a3839476622e8e5"
metafile = true

[[files]]
file = "mods/station-decoration.pw.toml"
hash = "5d6a0196e8af4554661ce0d7009e31fa4bdd5cbef7cca79b27c6f48b911380cd"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "371b68e257eaca322ca4e95f4aa8d95441d84110b69243dda818f743a0111ba5"
metafile = true

[[files]]
file = "mods/structurize.pw.toml"
hash = "c142309a161b3b50bbbb7bc0f1211a8461016c8681f94eb82a2b074cb3fba3db"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "3eede8a7ebafb69840153ff51dbc879b0232799e90a834ab6d71274b1316179f"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "4ddff1daf862f7e481a6c30c4cbb4bb32165f2c73cefc908dbf62b18f0d46a56"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "31883f2697767614c5b0671e9600c4e584c8e60be8062867667ddfc9d2624e23"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "fde3d3b1607636100e382dce1bba80ab4608ebfa1ef888a37b86bc8c7dcbafe5"
metafile = true

[[files]]
file = "mods/the-tube.pw.toml"
hash = "20395ea5ff447ffa4539019d73efd596059e26f42007d056cbc5002a6c5a375c"
metafile = true

[[files]]
file = "mods/towntalk.pw.toml"
hash = "32e0f6bce7adc5b09ba3350110ac4be7ee04e556db35ba1db97bacfabd31e4dc"
metafile = true

[[files]]
file = "mods/treechop.pw.toml"
hash = "de3524544e462fc53f0959a59c879a866730436083527ecf37852f4682b93786"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "eb48e8709268d9d4daeaba8d8844fa47e4e42fe2c6767ab39eca10e7852abf1e"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "8c1d85564af53d61caf23b502b60c494d33450a670093fdd3e2f412368682ecc"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "15f5872ee75d21be2e6cbd25669e423a2a764312562e5cdfdc4e34af160dc6d3"
metafile = true
