name = "NutAndJamPack"
author = "PJ"
version = "1.0.5b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17847e000046050c3dc9e7332001c3f2de80ec8b58c69fbc3435cfef5945d5f0"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
