name = "NutAndJamPack"
author = "PJ"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e56cde689f9796cb083a929de232ac035f0960af88c542fa01788626e4cd30c"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
