name = "NutAndJamPack"
author = "PJ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "055a708bfd816168640a46a6323d245222b4d7d57fc5ed4b40459195aa405d43"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
