name = "NutAndJamPack"
author = "PJ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f16af9e79557948b97e6616dd3070865ced2e71f31c1e3dd19d4384e753fbe1"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
