name = "NutAndJamPack"
author = "PJ"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "978246d83c927612b2f8d203baeae6f4c31f906dfb0c53bb8870edd3cf4aeef0"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
