name = "NutAndJamPack"
author = "PJ"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5df69dfd3188a078d53e245d7886e8b85c6d3f787a41355769093d1741b1059e"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
